#define COLOR_A 0
#define COLOR_Q 1
#define COLOR_S 2
#define COLOR_J 3
#define TOLL_DOLL 0
#define TOOL_BOMB 1
#define TOOL_BARRIER 2
#define PLACE_NUM 70
#define GIFT_PROPERTY 2000
#define GIFT_CREDIT 200
#define GIFT_GOD 5
#define LEVEL0 0
#define LEVEL1 1
#define LEVEL2 2
#define LEVEL3 3
#define ORDER_HELP 0
#define ORDER_QUIT -2
#define ORDER_ROLL -3
#define ORDER_Y -4
#define ORDER_N -5
#define ORDER_ROBOT -6
#define ORDER_QUERY -7
#define ORDER_WRONG -8
#define ORDER_STEP -9

#define HOSPITITAL_POS 17
#define TOOLHOUSE_POS 30
#define GIFT_HOUSE_POS 36
#define POISION_POS 46
#define MAGIC_PLACE_POS 60
#define MINE1_POS 61
#define MINE2_POS 62
#define MINE3_POS 63
#define MINE4_POS 64
#define MINE5_POS 65
#define MINE6_POS 66
