#define TOOL_DOLL 0
#define TOOL_BOMB 1
#define TOOL_BARRIER 2
#define PLACE_NUM 70
#define GIFT_PROPERTY 2000
#define GIFT_CREDIT 200
#define GIFT_GOD 5
#define LEVEL0 0
#define LEVEL1 1
#define LEVEL2 2
#define LEVEL3 3
#define ORDER_HELP 0
#define ORDER_QUIT -2
#define ORDER_ROLL -3
#define ORDER_Y -4
#define ORDER_N -5
#define ORDER_ROBOT -6
#define ORDER_QUERY -7
#define ORDER_WRONG -8
#define ORDER_STEP -9

#define HOSPITAL_POS 17
#define TOOLHOUSE_POS 30
#define GIFT_HOUSE_POS 36
#define PRISON_POS 46
#define MAGIC_PLACE_POS 60
#define MINE1_POS 64
#define MINE2_POS 65
#define MINE3_POS 66
#define MINE4_POS 67
#define MINE5_POS 68
#define MINE6_POS 69

#define HOSPITAL_ROLL_DELAY 3
#define PRISON_ROLL_DELAY 2

#define MINE1_CREDIT 60
#define MINE2_CREDIT 80
#define MINE3_CREDIT 40
#define MINE4_CREDIT 100
#define MINE5_CREDIT 80
#define MINE6_CREDIT 20

#define EMPTY_PIC '0'
#define BOMB_PIC '@'
#define BARRIER_PIC '#'
#define PRISON_PIC 'P'
#define HOSPITAL_PIC 'H'
#define MAGIC_PIC 'M'
#define TOOL_PIC 'T'
#define GIFT_PIC 'G'
#define MINE_PIC '$'
