#define TOLL_DOLL 0
#define TOOL_BOMB 1
#define TOOL_BARRIER 2
#define PLACE_NUM 70
#define GIFT_PROPERTY 2000
#define GIFT_CREDIT 200
#define GIFT_GOD 5
#define LEVEL0 0
#define LEVEL1 1
#define LEVEL2 2
#define LEVEL3 3
#define ORDER_HELP 0
#define ORDER_ROLL 1
#define ORDER_ROLE 2
#define ORDER_QUERY 3
#define ORDER_QUIT 4
#define ORDER_ROBOT 5
#define ORDER_SEQ 6
#define PRE_SET 7
